pub const REGISTERED_COMMANDS: &[&str] = &[
    "create_project",
    "open_project",
    "close_project",
    "get_project_session",
    "get_project_workspace",
    "save_block",
    "get_version_history",
    "create_checkpoint",
    "restore_checkpoint",
    "persist_operation_bundle",
    "append_review_event",
    "get_operation_audit",
    "store_provider_secret",
    "has_provider_secret",
    "delete_provider_secret",
];
